apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpc-orchestrator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_WITH_AWS_ACCOUNT_ID:role/ghost-protocol-prod-rpc-orchestrator-pod-role
