apiVersion: v1
kind: Service
metadata:
  name: rpc-orchestrator
  labels:
    app: rpc-orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: rpc-orchestrator
