apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# ArgoCD official installation (stable version)
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- namespace.yaml
- rbac-config.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml

# Custom configurations
patches:
- path: argocd-server-patch.yaml
  target:
    kind: Deployment
    name: argocd-server
