apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret-sync
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ghost-protocol
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      key: ghost-protocol/database
      property: url
  - secretKey: host
    remoteRef:
      key: ghost-protocol/database
      property: host
  - secretKey: port
    remoteRef:
      key: ghost-protocol/database
      property: port
  - secretKey: database
    remoteRef:
      key: ghost-protocol/database
      property: database
  - secretKey: username
    remoteRef:
      key: ghost-protocol/database
      property: username
  - secretKey: password
    remoteRef:
      key: ghost-protocol/database
      property: password
