apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret-sync
  labels:
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: ghost-protocol
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      key: ghost-protocol/redis
      property: url
  - secretKey: host
    remoteRef:
      key: ghost-protocol/redis
      property: host
  - secretKey: port
    remoteRef:
      key: ghost-protocol/redis
      property: port
  - secretKey: password
    remoteRef:
      key: ghost-protocol/redis
      property: password
