apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
- namespace.yaml
- operator-serviceaccount.yaml
- operator-rbac.yaml
- operator-deployment.yaml
- secretstore.yaml
- externalsecret-database.yaml
- externalsecret-redis.yaml
- externalsecret-openai.yaml
- externalsecret-huggingface.yaml

commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/part-of: ghost-protocol
